sentence = str(input("Enter your sentence: "))
word = str(input("Choose a word to replace: "))
new_word = str(input("Choose a word to replace your chosen word: "))
sentence.split(" ")
print(sentence.replace(word,new_word))
